default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: commit-msg
        name: conventional commit message
        entry: .githooks/commit-msg
        language: script
        stages: [commit-msg]
