default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
  - repo: local
    hooks:
      # ruff version comes from uv.lock
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]
      - id: commit-msg
        name: conventional commit message
        entry: .githooks/commit-msg
        language: script
        stages: [commit-msg]
